// dev/examples/react-dashboard/src/components/Sidebar.tsx
import type { Page } from "../App";
import { NAV_ITEMS } from "../data/nav";

interface SidebarProps {
  page: Page;
  onNavigate: (page: Page) => void;
}

/** Sidebar built entirely from data/nav.ts: change the badge count or add an item there, not here. */
export function Sidebar({ page, onNavigate }: SidebarProps) {
  return (
    <nav className="sidebar" aria-label="Main">
      <div className="sidebar-brand">Acme Store</div>
      <ul className="nav-list">
        {NAV_ITEMS.map((item) => (
          <li key={item.id}>
            <a
              href={item.href}
              className={item.page === page ? "nav-item nav-item-active" : "nav-item"}
              onClick={(event) => {
                event.preventDefault();
                if (item.page) onNavigate(item.page);
              }}
            >
              <span>{item.label}</span>
              {item.badge !== undefined && <span className="badge">{item.badge}</span>}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
}

// examples/vue-dashboard/src/components/Sidebar.vue
<script setup lang="ts">
import { NAV_ITEMS } from "../data/nav";
import type { Page } from "../types";

defineProps<{ page: Page }>();
const emit = defineEmits<{ navigate: [page: Page] }>();
</script>

<template>
  <!-- Built entirely from data/nav.ts: change the badge count or add an item there, not here. -->
  <nav class="sidebar" aria-label="Main">
    <div class="sidebar-brand">Acme Store</div>
    <ul class="nav-list">
      <li v-for="item in NAV_ITEMS" :key="item.id">
        <a
          :href="item.href"
          class="nav-item"
          :class="{ 'nav-item-active': item.page === page }"
          @click.prevent="item.page && emit('navigate', item.page)"
        >
          <span>{{ item.label }}</span>
          <span v-if="item.badge !== undefined" class="badge">{{ item.badge }}</span>
        </a>
      </li>
    </ul>
  </nav>
</template>
